var arr=[
	'https://v.qq.com/x/cover/2tr6sh7iw7wyvhl.html',
	'https://v.qq.com/x/cover/qgveju87b0mi9fi.html',
	'https://v.qq.com/x/cover/re9w4tpuinr8qxx.html',
	'https://v.qq.com/x/cover/8iec1jxf9bjom4g.html',
	'https://v.qq.com/x/cover/5x2qc4mq9ctyu10.html',
	'https://v.qq.com/x/cover/m3u8sfae4qeklnq.html',
	'https://v.qq.com/x/cover/7fxyrs5wa6iu3jg.html',
	'https://v.qq.com/x/cover/641dgjmod92qq07.html',
	'https://v.qq.com/x/cover/lgygfh6bgmimq87.html',
	'https://v.qq.com/x/cover/vu9sw3n7yrh7qwm.html',
	'https://v.qq.com/x/cover/jnsqcexmycxpcwr.html',
	'https://v.qq.com/x/cover/cltmsz5k25rt04w.html',
	'https://v.qq.com/x/cover/ei9w5141187ibo2.html',
	'https://v.qq.com/x/cover/n62tix4mc92a8bh.html',
	'https://v.qq.com/x/cover/gvuzs7kkl79lza1.html',
	'https://v.qq.com/x/cover/yoz60y87rdgl1vp.html',
	'https://v.qq.com/x/cover/l1zwovecxm9hg4p.html',
	'https://v.qq.com/x/cover/qg67m04ckextp6j.html',
	'https://v.qq.com/x/cover/jzhtr2cgy35ejz0.html',
	'https://v.qq.com/x/cover/jzhtr2cgy35ejz0.html',
	'https://v.qq.com/x/cover/6oysp96a4pku9up/n0024mvc1b8.html',
	'https://v.qq.com/x/cover/8iec1jxf9bjom4g.html',
	'https://v.qq.com/x/cover/0sradr5vk2at3ws.html',
	'https://v.qq.com/x/cover/5x2qc4mq9ctyu10.html',
	'https://v.qq.com/x/cover/641dgjmod92qq07.html',
	'https://v.qq.com/x/cover/41dicgms0277zoz.html',
	'https://v.qq.com/x/cover/x6plj3xkgdne0lz.html',
	'https://v.qq.com/x/cover/swbt7aqhm6lud3z.html',
	'https://v.qq.com/x/cover/09t5p6rdhrnxiig.html',
	'https://v.qq.com/x/cover/m8i6uooilmandtf.html',
	'https://v.qq.com/x/cover/3kxhegr3qwcfgsx.html',
	'https://v.qq.com/x/cover/b4e8yjwgokhr0lj.html',
	'https://v.qq.com/x/cover/ttphferxsi2xih6.html',
	'https://v.qq.com/x/cover/a7fcajz5pwkp9w4/y0025uvrur6.html',
	'https://v.qq.com/x/cover/1l93j61in2b72ki.html',
	'https://v.qq.com/x/cover/0sradr5vk2at3ws/x00253bck1b.html',
	'https://v.qq.com/x/cover/2tr6sh7iw7wyvhl/e053440gvfy.html',
	'https://v.qq.com/x/cover/sx5xljydk45g1pp/s0025ezj3iz.html',
	'https://v.qq.com/x/cover/7oyersb4w10gm2f/z0531bnad9o.html',
	'https://v.qq.com/x/cover/8ly4s55kfhsiu45/u0528tiskdm.html',
	'https://v.qq.com/x/cover/oon8w2cubbted9w/g0025zpn57l.html',
	'https://v.qq.com/x/cover/641dgjmod92qq07/s0025qn1pmf.html',
	'https://v.qq.com/x/cover/s6saq3s2eo58aum.html',
	'https://v.qq.com/x/cover/sj0lwa2rvbx551v.html',
	'https://v.qq.com/x/cover/ihl23ya1wr9t8hr.html',
	'https://v.qq.com/x/cover/8ly4s55kfhsiu45.html',
	'https://v.qq.com/x/cover/xv8ntbbe9ccug5o.html',
	'https://v.qq.com/x/cover/zf2z0xpqcculhcz.html',
	'https://v.qq.com/x/cover/lnnijsrcp2djcm5.html',
	'https://v.qq.com/x/cover/jtropm8st3kuqj8.html',
	'https://v.qq.com/x/cover/bpbktjcujie92tt.html',
	'https://v.qq.com/x/cover/vtxb95np45a6ooz.html',
	'https://v.qq.com/x/cover/p2t8xhtpypgcs19.html',
	'https://v.qq.com/x/cover/v2vfo5x38b624e1.html'
];



var jsipid=document.querySelectorAll(".jsipid");
for(var i=0;i<jsipid.length;i++){
	jsipid[i].href=arr[i];
}
